apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jql-to-slack-notifier.fullname" . }}
  labels:
    {{- include "jql-to-slack-notifier.labels" . | nindent 4 }}
data:
  queries.yaml: |
    {{- .Values.config | nindent 4 }}
