{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jql-to-slack-notifier.fullname" . }}
  labels:
    {{- include "jql-to-slack-notifier.labels" . | nindent 4 }}
type: Opaque
stringData:
  JIRA_API_TOKEN: {{ .Values.secrets.jiraApiToken | quote }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | quote }}
{{- end }}
